### ISSUE TITLE
打开侧边栏后，点击桌面其他区域，侧边栏不会关闭

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-sidebar#10]
After opening the sidebar, click on other areas of the desktop, the sidebar will not close

**Comment by kylin-ccn** [comment]
代码已于2月29日15点提交

**Comment by liumin0322** [comment]
20200302版本测试通过

**Comment by liumin0322** [comment]
20200321版本测试未通过，重新打开。

**Comment by liushanwen1997** [comment]
忘记打开点击桌面关闭侧边栏的开关

**Comment by Liang-zy** [comment]
20200328版本测试通过。
