### ISSUE TITLE
[internationalization] the name of the alarm clock is not international, it is still an alarm clock

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-sidebar#101]
![Screenshot from 2020-04-03 14-20-05](https://user-images.githubusercontent.com/48200161/78331867-7c1e9500-75b9-11ea-937c-e384410febc6.png)

**Comment by HuaYaDong1** [comment]
commit c34cb09778af4f478a0b011d615e33f1d3e67efc

**Comment by Liang-zy** [comment]
The 20200410 version passed the test
