### ISSUE TITLE
Occasional display abnormality of ukui-sidebar

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-sidebar#105]
![2020-04-02 20-52-09屏幕截图](https://user-images.githubusercontent.com/48200161/78423110-c32e8800-7696-11ea-9e89-fac591f4ce9a.png)

**Comment by liushanwen1997** [comment]
It has been resolved that the clipboard interface and sidebar interface are disordered due to topic switching. When the topic is switched, a redraw event will be issued, and the state machine will be initialized in the redraw event

**Comment by liushanwen1997** [comment]
侧边栏偶发性显示异常

**Comment by Liang-zy** [comment]
The 20200410 version passed the test
