### ISSUE TITLE
The clock in sidebar

### ISSUE THREAD

**Issue by sunshine-lcc** [ukui/ukui-sidebar#149]
The clock doesn't in effect when time is up, but jumps to the next time point behind it was configured

**Comment by HuaYaDong1** [comment]
> The clock doesn't in effect when time is up, but jumps to the next time point behind it was configured

Thank you for your correction,
But I don't quite understand what you mean,　Can you take a picture or describe the steps of reproduction．

**Comment by sunshine-lcc** [comment]
> > The clock doesn't in effect when time is up, but jumps to the next time point behind it was configured
> 
> Thank you for your correction,
> But I don't quite understand what you mean,　Can you take a picture or describe the steps of reproduction．

Thank you for your reply.
I found it just happen in the non-repetition situation like this case, but other situations are normal.
This is the released version of Ubuntu kylin 20.04 LTS
[16d266a8c39877754162a98784972225.mp4.zip](https://github.com/ukui/ukui-sidebar/files/4522910/16d266a8c39877754162a98784972225.mp4.zip)

**Comment by HuaYaDong1** [comment]
> > > The clock doesn't in effect when time is up, but jumps to the next time point behind it was configured
> > 
> > 
> > Thank you for your correction,
> > But I don't quite understand what you mean,　Can you take a picture or describe the steps of reproduction．
> 
> Thank you for your reply.
> I found it just happen in the non-repetition situation like this case, but other situations are normal.
> This is the released version of Ubuntu kylin 20.04 LTS
> [16d266a8c39877754162a98784972225.mp4.zip](https://github.com/ukui/ukui-sidebar/files/4522910/16d266a8c39877754162a98784972225.mp4.zip)

 Thank you for your support for Ubuntu kylin. I will modify the non repetitive function to only ring once. In the subsequent update．

**Comment by Liang-zy** [comment]
0723 test passed
