### ISSUE TITLE
The screen zoom is changed to 200%. After modifying the size of the taskbar, the clipboard and widget in the sidebar display abnormally

### ISSUE THREAD

**Issue by CrossCC** [ukui/ukui-sidebar#176]
Version：20.04LTS
ISO：ubuntukylin-20.04-050803-amd64.iso
Test environment：Lenovo  ThinkPad-X1-Yoga-4th
Test steps:
1. Set a zoom ratio of 200% in the control panel, log out and log in again
2. View the sidebar
3. Set the size of the taskbar to medium
4. View the sidebar
5. Set the size of the taskbar to a large size
6. View the sidebar
7. Restore the taskbar to a small size
8. View the sidebar
9. Click the widget, close the sidebar and click the sidebar

Desired result:
The sidebar displays normally

actual results:
2. When the task bar is the default small size, the "no clipping content" in the clipboard is not displayed completely
![侧边栏剪贴板](https://user-images.githubusercontent.com/33095911/81557491-a9334400-93be-11ea-9206-67b60a9a11bb.png)

4. When the task bar is medium-sized, the contents of the clipboard and the widget are displayed at the same time
![中尺寸任务栏](https://user-images.githubusercontent.com/33095911/81557508-af292500-93be-11ea-8fc0-0ba53ddfac39.png)

6. When the task bar is large, the contents of the clipboard and the widget are displayed at the same time
8. After the taskbar is restored to a small size, the clipboard and widget contents are displayed at the same time
9. Incomplete display of "No Clipping Content" in the clipboard in the sidebar

**Comment by CrossCC** [comment]
测试步骤：
1、控制面板中设置缩放比例200%，注销再登录
2、查看侧边栏
3、设置任务栏大小为中尺寸
4、查看侧边栏
5、设置任务栏大小为大尺寸
6、查看侧边栏
7、恢复任务栏大小为小尺寸
8、查看侧边栏
9、点击小插件，关闭侧边栏再点击侧边栏

期望结果：
侧边栏显示正常

实际结果：
2、任务栏为默认小尺寸时，剪贴板中“无剪贴内容”显示不全
4、任务栏为中尺寸时，剪贴板和小插件内容同时显示
6、任务栏为大尺寸时，剪贴板和小插件内容同时显示
8、任务栏恢复为小尺寸后，剪贴板和小插件内容同时显示
9、侧边栏剪贴板中“无剪贴内容”显示不全

**Comment by liushanwen1997** [comment]
当设置缩放比例200%的时候
1、小尺寸时，剪贴板中“无剪贴内容”显示不全  已解决;
2、中尺寸时，剪贴板和小插件内容同时显示    已解决;
3、大尺寸时，剪贴板和小插件内容同时显示    已解决;
4、任务栏恢复为小尺寸后，剪贴板和小插件内容同时显示  已解决;
5、当任务栏大尺寸时，剪贴板中“无剪贴内容”显示属于正常现象，剪贴板空白区域太小

**Comment by CrossCC** [comment]
20200521 test pass
