### ISSUE TITLE
接入双屏后，侧边栏在新接入屏幕弹出

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-sidebar#20]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200309-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、给笔记本外接屏幕

预期结果：外接后屏幕显示正常

实际结果：侧边栏默认打开在新接入屏幕

**Comment by kylin-ccn** [comment]
resolved

**Comment by liumin0322** [comment]
20200314版本测试通过
