### ISSUE TITLE
【ukui clock】 when there is an alarm clock or timer, there is no prompt message when the alarm plug-in is turned off

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-sidebar#211]
After counting down the alarm and setting the countdown or alarm, if you click the widget's close button, you will not be reminded of the countdown and alarm again, and the ukui-clock process is also closed, so you should not click the close button to prompt the user to choose at this location "Close alarm" or choose to run in the background

**Comment by HuaYaDong1** [comment]
Alarm window closing add background operation and direct closing options 
commit 
ea19e361ed53de09aaa09603edb6a4b680387bc1

**Comment by Liang-zy** [comment]
20200702 test passed
