### ISSUE TITLE
【Notebook】English name is not displayed completely

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-sidebar#216]
![Screenshot from 2020-06-22 18-06-53](https://user-images.githubusercontent.com/48200161/85275629-2cae7d80-b4b3-11ea-9ba2-4c6e9a155e9a.png)

**Comment by liushanwen1997** [comment]
建议将名字去掉Ukui, 设计的时候没有考虑到放不下英文名字的情况

**Comment by Liang-zy** [comment]
0723 test passed
