### ISSUE TITLE
 [ukui-notebook] Incomplete date display

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-sidebar#266]
![image](https://user-images.githubusercontent.com/39893452/87214015-ed5da900-c35b-11ea-9223-0e2ab6f6b68c.png)
Version: 20.04LTS 0702
Test environment: X1 Yoga
Test steps:
1. Open the ukui notebook
2. Switch the view to icon view
Expected result: no exceptions when switching views
Actual result: After switching views, the date cannot be fully displayed

**Comment by datyuesh** [comment]
07b35672a9275982a46fe20eca5dd4169c6f4e89

**Comment by datyuesh** [comment]
#271

**Comment by liumin0322** [comment]
20200717 test passed
