### ISSUE TITLE
Alarm clock reminder window, the mouse will be placed on the "remind later" window, a black box will pop up, resulting in incomplete font display

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-sidebar#286]
![image](https://user-images.githubusercontent.com/39893452/87932828-bd7e7600-cabe-11ea-8da4-7a127154a668.png)

**Comment by HuaYaDong1** [comment]
commit 740291f57e4154d810344e72bea46d04967b6ad4

**Comment by Liang-zy** [comment]
0723 test passed
