### ISSUE TITLE
[Alarm clock] The alarm clock crashes

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-sidebar#289]
1.默认设置-工作日-不勾选星期。设置闹钟，指定的时间后将没有提醒，然后闹钟将崩溃

2.添加一个闹钟-重复-不勾选星期，在指定时间后不再提醒，然后闹钟将崩溃

**Comment by HuaYaDong1** [comment]
commit c1b1df941188a8b2eadd26f2ce496efbf627da0b

**Comment by Liang-zy** [comment]
0723 test passed
