### ISSUE TITLE
[Feedback] Click the uploaded attachment, the ‘delete’ button is not visible

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-sidebar#315]
Version: 20.04 LTS
Test environment: ThinkPad X1 Dell 7060
Test steps:
Step 1. Sidebar-Widget-User Feedback / Start Menu-User Feedback
Step 2. Upload attachment-click the uploaded attachment
Expected results:
Step 1. Turn on user feedback
Step 2. Function is normal
actual results:
Step 1. Normal
Step 2. After clicking the uploaded attachment, the ‘delete’ button disappeared
![image](https://user-images.githubusercontent.com/39893452/89699960-72d57880-d95d-11ea-927f-8cddf9758fae.png)

**Comment by liumin0322** [comment]
20200818 test passed
