### ISSUE TITLE
Open French translation on weblate

### ISSUE THREAD

**Issue by roxfr** [ukui/ukui-sidebar#352]
Hi,
Could you open/release the French translation on weblate.ubuntukylin, please.
Thank you.
Regards,
Roxfr

**Comment by brsvh** [comment]
I have created it.

![IMG_20201213_192240](https://user-images.githubusercontent.com/63050399/102010383-aba4b480-3d78-11eb-8027-665a98ba2987.jpg)

Thx your contribution. 


You can close here.

**Comment by roxfr** [comment]
Ok, thanks
I finished translating ukui-sidebar.

![image](https://user-images.githubusercontent.com/52124613/102020012-d42baf00-3d76-11eb-816e-58d8a1330825.png)

**Comment by brsvh** [comment]
Your translations have been merged to `master`. #351
