### ISSUE TITLE
sidebar clipboard crashed

### ISSUE THREAD

**Issue by dou-y** [ukui/ukui-sidebar#4]
when Sidebar clipboard have more than two items, edit the first one, then edit the second, it will crashed
![图片](https://user-images.githubusercontent.com/59866026/74920615-6ab56b00-5407-11ea-92f8-30187d629dd5.png)
here are the steps:
1.copy some random text, then edit.
![图片](https://user-images.githubusercontent.com/59866026/74922468-37281000-540a-11ea-89cc-58102c5334f4.png)

2.copy another text, then edit. It will crash.

**Comment by liumin0322** [comment]
20200302版本未复现
