### ISSUE TITLE
【用户反馈】导致侧边栏崩溃

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-sidebar#44]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200321-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、首次打开用户反馈程序
2、填写必填项后，点击提交

预期结果：提交成功

实际结果：弹出提交失败-未知错误窗口，关闭该窗口后，侧边栏消失

**Comment by whailiang** [comment]
这个是因为点击退出之后调用了ｅｘｉｔ　所以导致侧边栏就退出了　　已经更改了调用函数，不会引起侧边栏崩溃

**Comment by Liang-zy** [comment]
20200328版本测试通过
