### ISSUE TITLE
【用户反馈】提交失败，报：与远程服务器的连接超时

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-sidebar#45]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200321-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开用户反馈程序
2、填写必填项后，点击提交

预期结果：提交成功

实际结果：等待一段时间后，弹出“问题提交失败：与远程服务器的连接超时”窗口，关闭该窗口，侧边栏崩溃，后台提示核心段错误

**Comment by moshengrenzenme** [comment]
此处可能有后端服务器的问题，不排除是因为交互时候身份验证导致的，毕竟直接访问都是超时，建议检查后端，开发再问问开发文档，两边排除

**Comment by whailiang** [comment]
已经与后端调通，网络好的情况下 不会出现超时情况。

**Comment by Liang-zy** [comment]
20200402版本测试通过
