### ISSUE TITLE
【用户反馈】勾选日志文件后，提示上传附件过大

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-sidebar#46]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200321-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、在用户反馈程序界面，填写必填项
2、勾选syslog或approt.log或dpkg.log，点击提交

预期结果：提交成功

实际结果：上传附件下，提示文件大小超过了3MB或文件格式不支持

**Comment by whailiang** [comment]
之前是对文件总大小做了３ＭＢ的过滤　这个限制有点小，所以增加到１０Ｍb

**Comment by liumin0322** [comment]
20200328版本测试通过。
