### ISSUE TITLE
【笔记本】保存文件后，侧边栏崩溃

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-sidebar#47]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200321-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开笔记本，新建笔记
2、输入内容后，点击保存

预期结果：保存至笔记本中

实际结果：弹出保存文件位置窗口，选择桌面后提交，侧边栏崩溃，后台提示段错误（核心已转储）

**Comment by Liang-zy** [comment]
20200328版本测试通过。
