### ISSUE TITLE
【用户反馈】添加附件后，侧边栏崩溃

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-sidebar#48]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200321-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开用户反馈程序，填写必填项
2、选择上传附件，添加附件

预期结果：成功添加附件

实际结果：点击添加后，侧边栏崩溃

**Comment by moshengrenzenme** [comment]
这个问题我定位到了，在add_fileinfo_model方法的添加到数据库附近，但是我不太会用qt的sqlite，我只会用原生的sql，抱歉，帮不上太大的忙

**Comment by whailiang** [comment]
之前添加附件崩溃是因为数据库的原因，程序作为插件使用的时候　如果有多个数据库　会出现这个问题，因为反馈程序　结束之后不需要保存数据，所以在添加附件时　不再使用数据库保存文件信息，使用qlist　现在不会出现崩溃情况

**Comment by Liang-zy** [comment]
20200328版本测试通过。
