### ISSUE TITLE
【用户反馈】邮箱的填写格式，未做判断

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-sidebar#49]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200321-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开用户反馈程序，填写必填项
2、在邮箱中填写123

预期结果：提交按钮不可选

实际结果：提交按钮置为可选

**Comment by whailiang** [comment]
在邮箱信息添加了正则表达式的判断

**Comment by Liang-zy** [comment]
20200328版本测试通过。
