### ISSUE TITLE
【双屏】侧边栏收起时，扩展屏可见收起动画效果，且留有一块黑色区域

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-sidebar#58]

**Comment by liushanwen1997** [comment]
Rewrite the previous sidebar animation, change the Layout structure, add the new Widget top window, put the Widget Layout before the sidebar into the new top window, implement all the sidebar animation in the top window, and only occupy the area in the top window.

**Comment by Liang-zy** [comment]
20200328版本测试通过。
