### ISSUE TITLE
【笔记本】添加笔记-输入字体颜色和背景一样，看不见

### ISSUE THREAD

**Issue by moshengrenzenme** [ukui/ukui-sidebar#66]
![微信图片_20200327140716](https://user-images.githubusercontent.com/33083187/77727022-5252f480-7034-11ea-8ebb-ea71045d83f4.png)

**Comment by moshengrenzenme** [comment]
这个不是没有显示，而是因为字体颜色是白色，所以肉眼不可见

**Comment by datyuesh** [comment]
commit 4835f19ca76f19a78b371811bef865e8de2c4d84

**Comment by Liang-zy** [comment]
20200402版本测试通过
