### ISSUE TITLE
【闹钟】添加闹钟界面显示铃响时间，和添加完成后显示不一致

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-sidebar#75]
版本：20.04LTS
iso：ubuntukylin-ukui3.0-20200328-amd64.iso
测试环境：联想启天M415-N000台式机
操作步骤：
1.打开闹钟-添加闹钟
2.保存

预期结果：显示闹钟铃响时间一致
实际结果：添加闹钟显示0小时22分钟后铃响，保存后显示0小时35后铃响。

**Comment by xiaodongliu-nudt** [comment]
跟 issue #78 关联

**Comment by HuaYaDong1** [comment]
commit 1a8651aadd59a326387988a0969585798e7d4de6

**Comment by Liang-zy** [comment]
20200402版本测试通过
