### ISSUE TITLE
添加闹钟提示的铃响时间不对

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-sidebar#78]
版本：20.04LTS
iso：ubuntukylin-ukui3.0-20200328-amd64.iso
测试环境：联想启天M415-N000台式机
操作步骤：
1.打开闹钟-添加闹钟

预期结果：显示闹钟铃响时间准确
实际结果： 添加闹钟的时间是16:30， 添加闹为16:40时显示响铃时间为：24小时10分后铃响

**Comment by HuaYaDong1** [comment]
commit 1a8651aadd59a326387988a0969585798e7d4de6

**Comment by Liang-zy** [comment]
20200402版本测试通过
