### ISSUE TITLE
添加闹钟-提醒时间时间5分钟为空

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-sidebar#79]
版本：20.04LTS
iso：ubuntukylin-ukui3.0-20200328-amd64.iso
测试环境：联想启天M415-N000台式机
操作步骤：
1.打开闹钟-添加闹钟
2.修改提醒铃声时间

预期结果： 文字显示正常
实际结果： 5分钟没有显示
![2020-03-28 19-43-46屏幕截图](https://user-images.githubusercontent.com/39893452/77822308-77c32980-712c-11ea-8640-ee6a835d0a05.png)

**Comment by HuaYaDong1** [comment]
commit 1a8651aadd59a326387988a0969585798e7d4de6

**Comment by Liang-zy** [comment]
20200402版本测试通过
