### ISSUE TITLE
【笔记本】添加笔记-输入字体颜色和背景一样，看不见

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-sidebar#83]
版本：20.04LTS
iso：ubuntukylin-ukui3.0-20200328-amd64.iso
测试环境：联想启天M415-N000台式机
操作步骤：
1.笔记本新建笔记

预期结果：字体显示正常
实际结果：输入后界面看不见输入的文字

**Comment by xiaodongliu-nudt** [comment]
Duplicate of #66
